#pragma once

#include "config_common.h"

// reduce size
// #define NO_DEBUG
// #define NO_PRINT
#define NO_ACTION_TAPPING
#define NO_ACTION_ONESHOT


/* sk6812 RGB LED */
#define RGB_DI_PIN D3

// NOTE: disable animations to save flash space
#undef RGBLIGHT_ANIMATIONS
#undef RGBLIGHT_EFFECT_ALTERNATING
#undef RGBLIGHT_EFFECT_BREATHING
#undef RGBLIGHT_EFFECT_CHRISTMAS
#undef RGBLIGHT_EFFECT_KNIGHT
#undef RGBLIGHT_EFFECT_RAINBOW_MOOD
// #undef RGBLIGHT_EFFECT_RAINBOW_SWIRL
#undef RGBLIGHT_EFFECT_RGB_TEST
#undef RGBLIGHT_EFFECT_RGB_SNAKE
#undef RGBLIGHT_EFFECT_STATIC_GRADIENT
#undef RGBLIGHT_EFFECT_TWINKLE

// #define RGBLIGHT_EFFECT_TWINKLE
// #define RGBLIGHT_MODE_TWINKLE 4
#define RGBLIGHT_EFFECT_RAINBOW_SWIRL
#define RGBLIGHT_DEFAULT_MODE RGBLIGHT_MODE_RAINBOW_SWIRL
// #define RGBLIGHT_MODE_RAINBOW_SWIRL 4
#define RGBLIGHT_DEFAULT_VAL RGBLIGHT_LIMIT_VAL - 50
#define RGBLED_NUM 58    // Number of LEDs
#define RGBLED_SPLIT { 29, 29 }

